### ISSUE TITLE
sys.stderr.write('ERROR: could not find fastq file(s) in:', output_dir_getfastq)

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#113]
@Hego-CCTB I'll fix this.
```
Traceback (most recent call last):
  File "/home/kfuku/miniconda3/bin/amalgkit", line 361, in <module>
    args.handler(args)
  File "/home/kfuku/miniconda3/bin/amalgkit", line 35, in command_quant
    quant_main(args)
  File "/home/kfuku/miniconda3/lib/python3.9/site-packages/amalgkit/quant.py", line 194, in quant_main
    run_quant(args, metadata, sra_id, index)
  File "/home/kfuku/miniconda3/lib/python3.9/site-packages/amalgkit/quant.py", line 108, in run_quant
    sys.stderr.write('ERROR: could not find fastq file(s) in:', output_dir_getfastq)
```

**Comment by kfuku52** [comment]
@Hego-CCTB Around line 108, you seem to have tried to catch FileNotFoundError raised by `get_newest_intermediate_file_extension()`, but it's redundant. If there is something to do with the error, we should do that in the function that raises the error, rather than trying to catch it later. I moved the codes around line 108 in `run_quant()` to `get_newest_intermediate_file_extension()`.
