### ISSUE TITLE
    print('layout = {}; Deleting unpaired file: {}'.format(sra_stat['layout'], unpaired_file)) NameError: name 'unpaired_file' is not defined

### ISSUE THREAD

**Issue by docxology** [kfuku52/amalgkit#133]
This is during amalgkit quant, and halts the process. 
Let me know what else I can try or other information to provide, thank you.

----------------------

Species: Apis mellifera
SRA Run ID: DRR129201
Looking for index folder in  ./
Kallisto index file found: ./index/Apis_mellifera.idx
Output file detected: ./quant/DRR129201/DRR129201_abundance.tsv
Continued. The output will not be overwritten. If you want to overwrite the results, set "--redo yes".

Species: Apis mellifera
SRA Run ID: SRR806711
Looking for index folder in  ./
Kallisto index file found: ./index/Apis_mellifera.idx
Output file was not detected: ./quant/SRR806711/SRR806711_abundance.tsv
Traceback (most recent call last):
  File "/home/tet/miniconda3/bin/amalgkit", line 370, in <module>
    args.handler(args)
  File "/home/tet/miniconda3/bin/amalgkit", line 43, in command_quant
    quant_main(args)
  File "/home/tet/miniconda3/lib/python3.9/site-packages/amalgkit/quant.py", line 191, in quant_main
    run_quant(args, metadata, sra_id, index)
  File "/home/tet/miniconda3/lib/python3.9/site-packages/amalgkit/quant.py", line 105, in run_quant
    ext = get_newest_intermediate_file_extension(sra_stat, work_dir=output_dir_getfastq)
  File "/home/tet/miniconda3/lib/python3.9/site-packages/amalgkit/util.py", line 432, in get_newest_intermediate_file_extension
    sra_stat = detect_layout_from_file(sra_stat)
  File "/home/tet/miniconda3/lib/python3.9/site-packages/amalgkit/util.py", line 475, in detect_layout_from_file
    print('layout = {}; Deleting unpaired file: {}'.format(sra_stat['layout'], unpaired_file))
NameError: name 'unpaired_file' is not defined

**Comment by kfuku52** [comment]
I updated amalgkit. Please let me know whether the latest version works fine.

**Comment by docxology** [comment]
Thank you! It is running fine now and catches a few hundred samples that were previously not working. I will update this or another issue if anything comes up.

**Comment by kfuku52** [comment]
I'm delighted to hear the bug fix worked well!
