### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#79]
```
Traceback (most recent call last):
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 33, in command_getfastq
    getfastq_main(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/getfastq.py", line 774, in getfastq_main
    sra_stat = get_sra_stat(sra_id, metadata, num_bp_per_sra)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/util.py", line 41, in get_sra_stat
    sra_stat['spot_length'] = int(original_spot_len)
ValueError: cannot convert float NaN to integer
```

**Comment by kfuku52** [comment]
This error is caused by an empty spot_length in the SRA metadata.
