### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'updated_metadata_dir'

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#82]
`amalgkit integrate` returned this error. I think this error does not depend on the input sample type. @Hego-CCTB Could you take a look?

```
Traceback (most recent call last):
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 89, in command_integrate
    integrate_main(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/integrate.py", line 104, in integrate_main
    data_available, data_unavailable = check_getfastq_outputs(args, sra_ids, metadata, args.out_dir)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/sanity.py", line 69, in check_getfastq_outputs
    if args.updated_metadata_dir:
AttributeError: 'Namespace' object has no attribute 'updated_metadata_dir'
```

**Comment by kfuku52** [comment]
The command was:
```
amalgkit integrate \
--out_dir ./ \
--fastq_dir ../local_fastq/${sp} \
--metadata ./metadata/metadata/metadata_03_curated_1900_01_01-2021_10_15.tsv \
--threads ${NSLOTS}
```

I'll share the metadata if it's difficult to reproduce on your end.

**Comment by kfuku52** [comment]
Another error appeared with the same command.
```
Traceback (most recent call last):
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/bin/amalgkit", line 89, in command_integrate
    integrate_main(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/integrate.py", line 131, in integrate_main
    tmp_metadata = get_fastq_stats(args)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/amalgkit/integrate.py", line 95, in get_fastq_stats
    tmp_metadata.loc[row,'spot_length']= tmp_stat_df.loc[0,'avg_len']
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 1060, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 831, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 1124, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexing.py", line 1073, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/generic.py", line 3738, in xs
    loc = index.get_loc(key)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'avg_len'
```

**Comment by Hego-CCTB** [comment]
My best guess is that this has something to do with seqkit.
avg_len is read from a temporary file, which is generated from seqkit output. But since amalgkit isn't terminated during execution of seqkit, I suspect this may be seqkit adjacent. Maybe a corrupted .tmp file, or some change in seqkit output due to an update, or something.

- Does this happen right away, or only for a particular SRA-ID/FASTQ file?
- The seqkit output is removed during the process, but we can preserve the tmp file by disabling line 76 in `integrate.py`. This could give some insight as to why there is no `ave_len`. I should implement the preservation of tmp files as a user option.

```
                    os.remove(tmp_file)
```

**Comment by kfuku52** [comment]
Sorry but I have no memory of any bugs from three months ago... Did you reproduce the error?

**Comment by Hego-CCTB** [comment]
Yeah, not your fault, of course!
`integrate` seems to work fine for me, so this may be particular to a certain SRA-ID or FASTQ file, or seqkit installation. 

I will implement an option for keeping the seqkit output, in case this comes up again in the future.

**Comment by Hego-CCTB** [comment]
Never closed this. The argument to keep the output is `--remove_tmp`
