### ISSUE TITLE
Exception: Empty value(s) of total_bases were detected in the metadata table.

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#96]
DRR258784
```
Fri Feb 25 02:51:26 JST 2022: Start: amalgkit getfastq
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/opt/conda/envs/biotools/bin/amalgkit", line 33, in command_getfastq
    getfastq_main(args)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/getfastq.py", line 825, in getfastq_main
    check_metadata_validity(metadata)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/getfastq.py", line 801, in check_metadata_validity
    raise Exception('Empty value(s) of total_bases were detected in the metadata table.')
Exception: Empty value(s) of total_bases were detected in the metadata table.
```

**Comment by kfuku52** [comment]
This bug is partly fixed in the above commit, but a new error arose. This error likely occurred due to yet-to-be-synced SRA from DDBJ to NCBI.

```
prefetch did not finish safely.
Traceback (most recent call last):
  File "/Users/kf/Dropbox/repos/amalgkit/amalgkit/amalgkit", line 380, in <module>
    args.handler(args)
  File "/Users/kf/Dropbox/repos/amalgkit/amalgkit/amalgkit", line 33, in command_getfastq
    getfastq_main(args)
  File "/Users/kf/Dropbox/repos/amalgkit/amalgkit/getfastq.py", line 877, in getfastq_main
    download_sra(metadata, sra_stat, args, sra_stat['output_dir'], overwrite=False)
  File "/Users/kf/Dropbox/repos/amalgkit/amalgkit/getfastq.py", line 308, in download_sra
    assert os.path.exists(sra_path), 'SRA file download failed: ' + sra_stat['sra_id']
AssertionError: SRA file download failed: DRR258784
```
