### ISSUE TITLE
/bin/sh: 1: bc: not found

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#99]
@Hego-CCTB `bc` is not available by default for some Linux distributes, so we should avoid it as much as possible. This is doable by replacing `$(NUM)/4` with `$[$(NUM)/4]`. I'll apply the change later.
```
/bin/sh: 1: bc: not found
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/opt/conda/envs/biotools/bin/amalgkit", line 89, in command_integrate
    integrate_main(args)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/integrate.py", line 134, in integrate_main
    get_fastq_stats(args)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/integrate.py", line 71, in get_fastq_stats
    total_spots = int(subprocess.check_output(total_spots_command, shell=True))
  File "/opt/conda/envs/biotools/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/biotools/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo $(zcat /gfe_data/transcriptome_assembly/fastp_fastq/Asarum_fudsinoiTBG157910/OY_18_2.fastq.gz | wc -l)/4|bc' returned non-zero exit status 127.
```

**Comment by kfuku52** [comment]
The above fix didn't work in my Singularity env.
```
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/amalgkit", line 378, in <module>
    args.handler(args)
  File "/opt/conda/envs/biotools/bin/amalgkit", line 89, in command_integrate
    integrate_main(args)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/integrate.py", line 129, in integrate_main
    get_fastq_stats(args)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/amalgkit/integrate.py", line 67, in get_fastq_stats
    total_spots = int(subprocess.check_output(total_spots_command, shell=True))
ValueError: invalid literal for int() with base 10: b'$[93204912/4]\n'
```

**Comment by kfuku52** [comment]
all fixed now
